p8105_hw6_jz3573
================
2023-12-02

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(p8105.datasets)
library(modelr)
library (readr)
library(viridis)
```

    ## Loading required package: viridisLite

``` r
library(ggplot2)
set.seed(1)
```

# Problem 1

## import data

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

    ## using cached file: /Users/jiangyuanzhu/Library/Caches/org.R-project.R/R/rnoaa/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2023-10-24 11:39:09.772076 (8.534)

    ## file min/max dates: 1869-01-01 / 2023-10-31

## generate 5000 bootstrap samples

``` r
boot_sample = function(df) {
  sample_frac(df, replace=TRUE)
}
```

``` r
boot_straps = 
  tibble(strap_number = 1:5000) %>% 
  mutate(
    strap_sample = map (strap_number, \(i) boot_sample(weather_df))
  )
set.seed(1)
```

## make a linear regression model

``` r
boot_lr=
  boot_straps %>% 
  mutate(
    models = map (.x= strap_sample, ~ lm (tmax ~ tmin + prcp, data= .x )),
    glance = map (models, broom::glance),
    results = map (models, broom :: tidy),
    r_squared = map (glance, \ (df) pull (df, r.squared)),
    log = map(results, \(df) log(abs(df$estimate[2] * df$estimate[3])))
  )  %>% 
  select(strap_number, r_squared, log) |>
  mutate(
    r_squared = as.numeric(r_squared),
    log = as.numeric(log)
  )
```

## plot the distribution of estimates of r-square

``` r
boot_lr %>% 
  ggplot (aes(x=r_squared)) +
  geom_density() +
  labs(title = "distribution of r-square")
```

![](p8105_hw6_jz3573_files/figure-gfm/distribution%20of%20r-square-1.png)<!-- -->
The distribution of r_square is centered between 0.90 and 0.94, which
means that the perception and tmin can predicts more than 90 % of tmax.
In antoher word, the model is a good predicion model.

## plot the distribution of estimate of log(b1\*b2)

``` r
boot_lr %>% 
  ggplot (aes(x=log)) +
  geom_density() +
  labs (title = "distribution of log(b1*b2)" )
```

![](p8105_hw6_jz3573_files/figure-gfm/plot%20the%20distribution%20of%20log(b1*b2)-1.png)<!-- -->
The distribution of log (b1\*b2) is left-skewed and is centered around
-5

## 95% confidence interval for r_square

``` r
boot_lr %>% 
  summarize (
    r_squared_2.5 = quantile (r_squared, 0.025),
    r_squared_97.5 = quantile (r_squared, 0.9725)
  ) %>% 
  knitr::kable (digits = 3)
```

| r_squared_2.5 | r_squared_97.5 |
|--------------:|---------------:|
|         0.889 |           0.94 |

The 95% confidence interval for r_square is (0.889, 0.940)

## 95% confidence interval for log(b1\*b2)

``` r
boot_lr %>% 
  summarize (
    log_2.5 = quantile(log,0.025),
    log_97.5 = quantile(log, 0.975)
  ) %>% 
  knitr::kable (digits = 3)
```

| log_2.5 | log_97.5 |
|--------:|---------:|
|  -8.589 |   -4.592 |

The 95% confidence interval for r_square is (-8.589, 4.592)

# Question 3

## load and clean the data

load the data

``` r
birthwt_df = 
  read_csv( "./data/birthweight.csv") %>% 
  janitor::clean_names() 
```

    ## Rows: 4342 Columns: 20
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

convert numberic variable to character variable

``` r
birthwt_df %>% 
  mutate (babysex = as.factor(babysex),
          frace = as.factor(frace),
          malform = as.factor (mrace),
          mrace = as.factor (mrace))  %>% 
  select(bwt, everything())
```

    ## # A tibble: 4,342 × 20
    ##      bwt babysex bhead blength delwt fincome frace gaweeks malform menarche
    ##    <dbl> <fct>   <dbl>   <dbl> <dbl>   <dbl> <fct>   <dbl> <fct>      <dbl>
    ##  1  3629 2          34      51   177      35 1        39.9 1             13
    ##  2  3062 1          34      48   156      65 2        25.9 2             14
    ##  3  3345 2          36      50   148      85 1        39.9 1             12
    ##  4  3062 1          34      52   157      55 1        40   1             14
    ##  5  3374 2          34      52   156       5 1        41.6 1             13
    ##  6  3374 1          33      52   129      55 1        40.7 1             12
    ##  7  2523 2          33      46   126      96 2        40.3 2             14
    ##  8  2778 2          33      49   140       5 1        37.4 1             12
    ##  9  3515 1          36      52   146      85 1        40.3 1             11
    ## 10  3459 1          33      50   169      75 2        40.7 2             12
    ## # ℹ 4,332 more rows
    ## # ℹ 10 more variables: mheight <dbl>, momage <dbl>, mrace <fct>, parity <dbl>,
    ## #   pnumlbw <dbl>, pnumsga <dbl>, ppbmi <dbl>, ppwt <dbl>, smoken <dbl>,
    ## #   wtgain <dbl>

check missing data

``` r
is.na((birthwt_df)) %>% 
  colSums()
```

    ##  babysex    bhead  blength      bwt    delwt  fincome    frace  gaweeks 
    ##        0        0        0        0        0        0        0        0 
    ##  malform menarche  mheight   momage    mrace   parity  pnumlbw  pnumsga 
    ##        0        0        0        0        0        0        0        0 
    ##    ppbmi     ppwt   smoken   wtgain 
    ##        0        0        0        0

There is no missing data.

## build a regression model

My hypothesis is that the birthweight is related with babysex, delwt,
fincome,gaweeks and smoken, which is built on biological knowlodge and
intuition.

``` r
model = lm (bwt ~ babysex + delwt + fincome +gaweeks + smoken, data = birthwt_df)
```

## show a plot of model residuals

``` r
birthwt_df %>% 
  add_predictions(model) %>% 
  add_residuals(model) %>% 
  ggplot(aes (x=pred, y=resid)) +
  geom_point() +
  labs(title = "residuals vs fitted values") +
  xlab ("fitted values") +
  ylab ("residuals")
```

![](p8105_hw6_jz3573_files/figure-gfm/plot%20for%20model%20residuals-1.png)<!-- -->
It seems that the model produce a great amount of residuals.

## Compare my model to two others

create the cross-validation dataset

``` r
cv_df =
  crossv_mc(birthwt_df,100) %>% 
  mutate(
    train = map (train, as_tibble),
    test =  map (test, as_tibble)
  )
```

calculate the root-mean-standard-error for each dataset : my model,
model 0 :lm bwt ~ babysex + delwt + fincome +gaweeks + smoken model 1:
lm bwt ~ blength + gaweeks model 2: lm bwt ~ bhead \* blength \* babysex

``` r
outcome  =
  cv_df %>% 
  mutate (
    model_0 = map (train, ~ lm(bwt ~ babysex  + delwt + fincome +gaweeks + smoken, data = birthwt_df )),
   model_1 = map(train, ~ lm (bwt ~ blength + gaweeks, data = birthwt_df)) ,
   model_2 = map (train, ~ lm (bwt ~ bhead * blength * babysex, data= birthwt_df))
  ) %>% 
    mutate (
      rmse_0 = map2_dbl(.x=model_0, .y=test, ~ rmse(model=.x, data = .y) ),
      rmse_1 = map2_dbl(.x=model_1, .y=test, ~ rmse(model=.x, data = .y) ),
      rmse_2 = map2_dbl(.x=model_2, .y=test, ~ rmse(model=.x, data = .y) ))
```

calculate the mean of rmse

``` r
outcome %>% 
  summarize(
    mean_0 = mean (rmse_0),
    mean_1 = mean (rmse_1),
    mean_2 = mean (rmse_2)
  ) %>% 
  knitr :: kable()
```

|   mean_0 |   mean_1 |   mean_2 |
|---------:|---------:|---------:|
| 441.5007 | 331.5343 | 286.6891 |

Model 2 has less sd than model 1 in average, and model 1 has less sd
than model 0. It seems that model 2 is most precise.

Make violin plots for three models

``` r
outcome |>
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin(aes(fill = model)) +
  labs(
    title = "Violin plot of RMSE of the models "
  )
```

![](p8105_hw6_jz3573_files/figure-gfm/voilin%20plot-1.png)<!-- -->
